NUMBER_OF_VERSES = 31102
NUMBER_OF_CHAPTERS = 1189
NUMBER_OF_BOOKS = 66
LAST_VERSE_NAME = 21
LAST_CHAPTER_NAME = 22
VERSE_AUDIO_URL_STEM = "http://www.ebibleaudio.com/Radio/MP3%2032800%20Single%20Verse%20Files"
VERSE_AUDIO_BOOK_ABBREV ={
  "Philippians" => "PHP",
  "Philemon" => "PHM",
  "Jude" => "JDE" 
}