production:
  solr:
    hostname: cbarr.dyndns.org
    port: 8983
    log_level: WARNING

development:
  solr:
    hostname: cbarr.dyndns.org
    port: 8982
    log_level: INFO

test:
  solr:
    hostname: cbarr.dyndns.org
    port: 8981
    log_level: WARNING